########################
####### MESSAGES #######
########################

messages:
  prefix: "&8&l[&6CosmicCosmetics&8]&r "

  no-permission: "{prefix}&cYou do not have the permission to do that!"
  must-be-a-player: "{prefix}&cYou must be a player to do that!"

settings:
  update-checker: true