########################
####### MESSAGES #######
########################

no-permission: "&cYou do not have the permission to do that!"
must-be-a-player: "&cYou must be a player to do that!"
mysql-connection-fail: "&cFailed to connect to MySQL server!"
mysql-connection-success: "&aSuccessfully connected to MySQL server!"
mysql-query-fail: "&cFailed to execute query!"

########################
####### DATABASE #######
########################

database:
  host: localhost
  port: 3306
  username: root
  password: password
  database: database